// Admin/CEO feature inventory. Code is the source of truth for what is held and why.
export type InventoryItem = {
  module: string;
  item: string;
  state: "Active" | "Built, not on live site" | "Held" | "Draft" | "Placeholder" | "Closed";
  why: string;
  missing: string;
  backend: string;
  test: string;
  link?: string;
};

export const FEATURE_INVENTORY: InventoryItem[] = [
  { module: "Nexus", item: "Introductions (consent, staff send, partner portal)", state: "Active", why: "Enabled 2026-09-25 18:46 UTC for eligible approved partners.", missing: "A published, approved partner in an open category (currently none).", backend: "Live: real requests can be introduced only to published partners.", test: "Done. Repeat full TEST flow after any consent wording change.", link: "/staff/inquiries" },
  { module: "Nexus", item: "Help form, member directory, founder request history pages", state: "Built, not on live site", why: "Automatic preview build fails intermittently.", missing: "Lovable support fix and a run of stable automatic builds.", backend: "None; backend already live.", test: "Repeated automatic builds pass; recheck routes signed in and signed out.", link: "/nexus/help" },
  { module: "Nexus", item: "Partner listings (all categories)", state: "Held", why: "No listing publication authorized.", missing: "Owner authorization per listing.", backend: "Publishing makes the profile visible to members and eligible for real introductions.", test: "Publication gates, closed-type refusal, member projection check." , link: "/admin/applications" },
  { module: "Nexus", item: "University, Banking, Insurance categories", state: "Active", why: "Opened for applications and help requests 2026-09-25.", missing: "Listings still need separate authorization.", backend: "Category flags open on shared backend.", test: "Done.", link: "/staff" },
  { module: "Nexus", item: "Homepage partner showcase", state: "Held", why: "Only shows partners with approved status and explicit display permission.", missing: "At least one published partner with display permission.", backend: "None.", test: "Only permitted partners appear; closed categories never appear." },
  { module: "Accounts", item: "Terms acknowledgement at sign-up", state: "Draft", why: "Final Terms wording not approved.", missing: "Approved Terms text and version.", backend: "Would store acknowledgement version and time per account.", test: "Sign-up blocked without active acknowledgement; version recorded." },
  { module: "Nexus", item: "Help-form rate-limit record cleanup", state: "Held", why: "Retention period not decided.", missing: "Owner-approved retention period (30 days proposed).", backend: "Scheduled deletion of old rate-limit keys.", test: "Old records removed, recent kept, limits still enforced." },
  { module: "Content", item: "Public pricing", state: "Held", why: "Pricing publication is blocked in the content portal.", missing: "Owner-approved, reconciled pricing schedule (OPSIRIX_33 missing).", backend: "Pricing block could be published.", test: "Preview, publish, restore; no page shows unapproved prices.", link: "/staff/content" },
  { module: "Content", item: "Most page copy and FAQs", state: "Draft", why: "Still written in code; only some sections are editable.", missing: "Decide which sections to move into the portal.", backend: "New content blocks.", test: "Draft, preview, publish, restore per section.", link: "/staff/content" },
  { module: "OS", item: "Founder workspace beyond company, members and staff access", state: "Placeholder", why: "No approved spec.", missing: "Approved OS spec.", backend: "Not built.", test: "Defined per approved spec.", link: "/workspace" },
  { module: "Launch", item: "Launch intake and coordination", state: "Built, not on live site", why: "Approved replacement intake is implemented for owner review; public Launch remains off.", missing: "Owner screen/wording approval, retention decision, TEST cleanup decision and staged release checks.", backend: "Live: intake, review, assignment and company-scope rules through migration 0059. New intake saves require current company membership.", test: "TEST allowlist only: founder draft/resume/review/scope/submission/correction; Admin assignment; assigned and unassigned Operations Lead at desktop and 390px.", link: "/launch" },
  { module: "Accounts", item: "First-time guided tours", state: "Built, not on live site", why: "Role-based orientation is ready in preview for owner review.", missing: "Complete isolated role/revocation regression and deployment smoke tests.", backend: "Live: per-account, role and tour-version progress with role revalidation on every save; tour content remains unpublished.", test: "Member first use, skip, replay, keyboard and 390px; dual-role switcher-first flow; partner orientation and protected-link denial checked.", link: "/account" },
  { module: "Flow", item: "Scheduling and follow-up", state: "Placeholder", why: "Marketing page only.", missing: "Approved spec.", backend: "Not built.", test: "Defined per approved spec." },
  { module: "Grid", item: "Criteria v3 self-assessment and staff evidence review (14 active checks)", state: "Built, not on live site", why: "Approved 2026-09-29 for preview; scoring stays off.", missing: "Owner review of screens; 11 specialist checks stay inactive until reviewed.", backend: "Live: migration 0056 (criteria answers, version per record, save rules).", test: "Done: 45/45 rule checks, browser founder and staff flows, 16/16 cross-company checks.", link: "/grid" },
  { module: "Grid", item: "Incident 2026-09-29: TEST draft saved to D-Global Technologies LLC", state: "Closed", why: "During browser testing the TEST owner account saved a founder draft to D-Global, a company that account created and owns. Save rule worked as designed; the test picked the wrong company.", missing: "None. Draft deleted; its one history entry kept unchanged. No other member, no notification. Rule: no tests against real companies.", backend: "No rule change needed. Draft and its answers removed on the shared backend on 2026-09-29.", test: "16/16 direct cross-company create, read, update, submit attempts denied (founder and staff), TEST companies only." },
  { module: "Core", item: "Core module", state: "Placeholder", why: "Marketing page only.", missing: "Approved spec.", backend: "Not built.", test: "Defined per approved spec." },
  { module: "Vault", item: "Private document storage", state: "Held", why: "Awaiting privacy design and security review.", missing: "Client-held key design, independent security review, retention and incident plan (OPSIRIX_29).", backend: "Not built. Nexus storage must not be reused.", test: "Independent review; no encryption claims until verified." },
  { module: "AI", item: "AI features (page marked Coming Soon)", state: "Held", why: "Awaiting privacy and security review.", missing: "Approval rules before any content reaches an AI provider; security review.", backend: "Not built.", test: "Explicit per-item approval before sending; review sign-off." },
  { module: "Staff Console", item: "Audit search", state: "Held", why: "Approved but not yet built.", missing: "None; ready to build.", backend: "Read-only search over audit history (Admin only).", test: "Admin can search; other roles denied.", link: "/staff" },
  { module: "Staff Console", item: "Founder Success and Technology Liaison roles", state: "Held", why: "Duties and access not specified.", missing: "Written duties and access limits.", backend: "New roles and permissions.", test: "Role-by-role browser and direct-request denial tests." },
  { module: "Accounts", item: "D-Global Technologies LLC workspace: real-name record, TEST-owned, provenance unverified", state: "Held", why: "Owner has not confirmed it is an authorized production record. Excluded from TEST cleanup and real-client workflows; not renamed or deleted.", missing: "Owner decision: retain, transfer or close.", backend: "OPX-000021. Created 2026-09-27 18:38 UTC by opsirix+test-owner@gmail.com via Create company workspace. 1 member (that TEST account, owner). Linked records: 0 boards, 0 tasks, 0 Core requests, 0 Grid records, 0 grants, 0 notifications; 2 history entries (workspace created; incident draft saved).", test: "No tests may use it (not on TEST allowlist)." },
  { module: "Nexus", item: "Partner organization membership and shared introduction notes", state: "Draft", why: "Proposed separately. Today only the recipient partner account sees its own notes (tested rule, unchanged).", missing: "Owner-approved access design: who joins a partner organization, who approves, which notes are shared.", backend: "New membership table and note-sharing rules (not built).", test: "Non-recipient members denied until shared; removal ends access; consent fields never widen; direct-request denials." },
  { module: "Release", item: "Publish preview to opsirix.lovable.app", state: "Held", why: "Intermittent automatic build failure.", missing: "Build fix and owner go-ahead. Domain routed by owner via GitHub; DNS unchanged.", backend: "None.", test: "Stable automatic builds; public and signed-in route checks after publish." },
];
