/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as ImmigrantFoundersRouteImport } from './routes/immigrant-founders'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForUniversitiesRouteImport } from './routes/for-universities'
import { Route as ForPartnersRouteImport } from './routes/for-partners'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EarlyStageFoundersRouteImport } from './routes/early-stage-founders'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlatformIndexRouteImport } from './routes/platform.index'
import { Route as PlatformVaultRouteImport } from './routes/platform.vault'
import { Route as PlatformStudioRouteImport } from './routes/platform.studio'
import { Route as PlatformOsRouteImport } from './routes/platform.os'
import { Route as PlatformNexusRouteImport } from './routes/platform.nexus'
import { Route as PlatformLaunchRouteImport } from './routes/platform.launch'
import { Route as PlatformGridRouteImport } from './routes/platform.grid'
import { Route as PlatformFlowRouteImport } from './routes/platform.flow'
import { Route as PlatformCoreRouteImport } from './routes/platform.core'
import { Route as PlatformAiRouteImport } from './routes/platform.ai'
import { Route as NexusHelpRouteImport } from './routes/nexus.help'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated.workspace.index'
import { Route as AuthenticatedStaffIndexRouteImport } from './routes/_authenticated.staff.index'
import { Route as AuthenticatedPartnerIndexRouteImport } from './routes/_authenticated.partner.index'
import { Route as AuthenticatedStaffInquiriesRouteImport } from './routes/_authenticated.staff.inquiries'
import { Route as AuthenticatedStaffContentRouteImport } from './routes/_authenticated.staff.content'
import { Route as AuthenticatedStaffAccessRouteImport } from './routes/_authenticated.staff.access'
import { Route as AuthenticatedPartnerServicesRouteImport } from './routes/_authenticated.partner.services'
import { Route as AuthenticatedPartnerProfileRouteImport } from './routes/_authenticated.partner.profile'
import { Route as AuthenticatedPartnerOnboardingRouteImport } from './routes/_authenticated.partner.onboarding'
import { Route as AuthenticatedPartnerApplyRouteImport } from './routes/_authenticated.partner.apply'
import { Route as AuthenticatedNexusDirectoryRouteImport } from './routes/_authenticated.nexus.directory'
import { Route as AuthenticatedAdminPreviewRouteImport } from './routes/_authenticated.admin.preview'
import { Route as AuthenticatedAdminApplicationsRouteImport } from './routes/_authenticated.admin.applications'
import { Route as AuthenticatedAdminReviewIdRouteImport } from './routes/_authenticated.admin.review.$id'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const ImmigrantFoundersRoute = ImmigrantFoundersRouteImport.update({
  id: '/immigrant-founders',
  path: '/immigrant-founders',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForUniversitiesRoute = ForUniversitiesRouteImport.update({
  id: '/for-universities',
  path: '/for-universities',
  getParentRoute: () => rootRouteImport,
} as any)
const ForPartnersRoute = ForPartnersRouteImport.update({
  id: '/for-partners',
  path: '/for-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EarlyStageFoundersRoute = EarlyStageFoundersRouteImport.update({
  id: '/early-stage-founders',
  path: '/early-stage-founders',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformIndexRoute = PlatformIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformVaultRoute = PlatformVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformStudioRoute = PlatformStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformOsRoute = PlatformOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformNexusRoute = PlatformNexusRouteImport.update({
  id: '/nexus',
  path: '/nexus',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformLaunchRoute = PlatformLaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformGridRoute = PlatformGridRouteImport.update({
  id: '/grid',
  path: '/grid',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformFlowRoute = PlatformFlowRouteImport.update({
  id: '/flow',
  path: '/flow',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformCoreRoute = PlatformCoreRouteImport.update({
  id: '/core',
  path: '/core',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformAiRoute = PlatformAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => PlatformRoute,
} as any)
const NexusHelpRoute = NexusHelpRouteImport.update({
  id: '/nexus/help',
  path: '/nexus/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffIndexRoute = AuthenticatedStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnerIndexRoute =
  AuthenticatedPartnerIndexRouteImport.update({
    id: '/partner/',
    path: '/partner/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffInquiriesRoute =
  AuthenticatedStaffInquiriesRouteImport.update({
    id: '/staff/inquiries',
    path: '/staff/inquiries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffContentRoute =
  AuthenticatedStaffContentRouteImport.update({
    id: '/staff/content',
    path: '/staff/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedStaffAccessRoute =
  AuthenticatedStaffAccessRouteImport.update({
    id: '/staff/access',
    path: '/staff/access',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerServicesRoute =
  AuthenticatedPartnerServicesRouteImport.update({
    id: '/partner/services',
    path: '/partner/services',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerProfileRoute =
  AuthenticatedPartnerProfileRouteImport.update({
    id: '/partner/profile',
    path: '/partner/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerOnboardingRoute =
  AuthenticatedPartnerOnboardingRouteImport.update({
    id: '/partner/onboarding',
    path: '/partner/onboarding',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartnerApplyRoute =
  AuthenticatedPartnerApplyRouteImport.update({
    id: '/partner/apply',
    path: '/partner/apply',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNexusDirectoryRoute =
  AuthenticatedNexusDirectoryRouteImport.update({
    id: '/nexus/directory',
    path: '/nexus/directory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPreviewRoute =
  AuthenticatedAdminPreviewRouteImport.update({
    id: '/admin/preview',
    path: '/admin/preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminApplicationsRoute =
  AuthenticatedAdminApplicationsRouteImport.update({
    id: '/admin/applications',
    path: '/admin/applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminReviewIdRoute =
  AuthenticatedAdminReviewIdRouteImport.update({
    id: '/admin/review/$id',
    path: '/admin/review/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/early-stage-founders': typeof EarlyStageFoundersRoute
  '/faq': typeof FaqRoute
  '/for-partners': typeof ForPartnersRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/immigrant-founders': typeof ImmigrantFoundersRoute
  '/platform': typeof PlatformRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
  '/nexus/help': typeof NexusHelpRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/core': typeof PlatformCoreRoute
  '/platform/flow': typeof PlatformFlowRoute
  '/platform/grid': typeof PlatformGridRoute
  '/platform/launch': typeof PlatformLaunchRoute
  '/platform/nexus': typeof PlatformNexusRoute
  '/platform/os': typeof PlatformOsRoute
  '/platform/studio': typeof PlatformStudioRoute
  '/platform/vault': typeof PlatformVaultRoute
  '/platform/': typeof PlatformIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/nexus/directory': typeof AuthenticatedNexusDirectoryRoute
  '/partner/apply': typeof AuthenticatedPartnerApplyRoute
  '/partner/onboarding': typeof AuthenticatedPartnerOnboardingRoute
  '/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/partner/services': typeof AuthenticatedPartnerServicesRoute
  '/staff/access': typeof AuthenticatedStaffAccessRoute
  '/staff/content': typeof AuthenticatedStaffContentRoute
  '/staff/inquiries': typeof AuthenticatedStaffInquiriesRoute
  '/partner/': typeof AuthenticatedPartnerIndexRoute
  '/staff/': typeof AuthenticatedStaffIndexRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/admin/review/$id': typeof AuthenticatedAdminReviewIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/early-stage-founders': typeof EarlyStageFoundersRoute
  '/faq': typeof FaqRoute
  '/for-partners': typeof ForPartnersRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/immigrant-founders': typeof ImmigrantFoundersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
  '/nexus/help': typeof NexusHelpRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/core': typeof PlatformCoreRoute
  '/platform/flow': typeof PlatformFlowRoute
  '/platform/grid': typeof PlatformGridRoute
  '/platform/launch': typeof PlatformLaunchRoute
  '/platform/nexus': typeof PlatformNexusRoute
  '/platform/os': typeof PlatformOsRoute
  '/platform/studio': typeof PlatformStudioRoute
  '/platform/vault': typeof PlatformVaultRoute
  '/platform': typeof PlatformIndexRoute
  '/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/nexus/directory': typeof AuthenticatedNexusDirectoryRoute
  '/partner/apply': typeof AuthenticatedPartnerApplyRoute
  '/partner/onboarding': typeof AuthenticatedPartnerOnboardingRoute
  '/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/partner/services': typeof AuthenticatedPartnerServicesRoute
  '/staff/access': typeof AuthenticatedStaffAccessRoute
  '/staff/content': typeof AuthenticatedStaffContentRoute
  '/staff/inquiries': typeof AuthenticatedStaffInquiriesRoute
  '/partner': typeof AuthenticatedPartnerIndexRoute
  '/staff': typeof AuthenticatedStaffIndexRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/admin/review/$id': typeof AuthenticatedAdminReviewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/directory': typeof DirectoryRoute
  '/early-stage-founders': typeof EarlyStageFoundersRoute
  '/faq': typeof FaqRoute
  '/for-partners': typeof ForPartnersRoute
  '/for-universities': typeof ForUniversitiesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/immigrant-founders': typeof ImmigrantFoundersRoute
  '/platform': typeof PlatformRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/join/$code': typeof JoinCodeRoute
  '/nexus/help': typeof NexusHelpRoute
  '/platform/ai': typeof PlatformAiRoute
  '/platform/core': typeof PlatformCoreRoute
  '/platform/flow': typeof PlatformFlowRoute
  '/platform/grid': typeof PlatformGridRoute
  '/platform/launch': typeof PlatformLaunchRoute
  '/platform/nexus': typeof PlatformNexusRoute
  '/platform/os': typeof PlatformOsRoute
  '/platform/studio': typeof PlatformStudioRoute
  '/platform/vault': typeof PlatformVaultRoute
  '/platform/': typeof PlatformIndexRoute
  '/_authenticated/admin/applications': typeof AuthenticatedAdminApplicationsRoute
  '/_authenticated/admin/preview': typeof AuthenticatedAdminPreviewRoute
  '/_authenticated/nexus/directory': typeof AuthenticatedNexusDirectoryRoute
  '/_authenticated/partner/apply': typeof AuthenticatedPartnerApplyRoute
  '/_authenticated/partner/onboarding': typeof AuthenticatedPartnerOnboardingRoute
  '/_authenticated/partner/profile': typeof AuthenticatedPartnerProfileRoute
  '/_authenticated/partner/services': typeof AuthenticatedPartnerServicesRoute
  '/_authenticated/staff/access': typeof AuthenticatedStaffAccessRoute
  '/_authenticated/staff/content': typeof AuthenticatedStaffContentRoute
  '/_authenticated/staff/inquiries': typeof AuthenticatedStaffInquiriesRoute
  '/_authenticated/partner/': typeof AuthenticatedPartnerIndexRoute
  '/_authenticated/staff/': typeof AuthenticatedStaffIndexRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/_authenticated/admin/review/$id': typeof AuthenticatedAdminReviewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/directory'
    | '/early-stage-founders'
    | '/faq'
    | '/for-partners'
    | '/for-universities'
    | '/how-it-works'
    | '/immigrant-founders'
    | '/platform'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/join/$code'
    | '/nexus/help'
    | '/platform/ai'
    | '/platform/core'
    | '/platform/flow'
    | '/platform/grid'
    | '/platform/launch'
    | '/platform/nexus'
    | '/platform/os'
    | '/platform/studio'
    | '/platform/vault'
    | '/platform/'
    | '/admin/applications'
    | '/admin/preview'
    | '/nexus/directory'
    | '/partner/apply'
    | '/partner/onboarding'
    | '/partner/profile'
    | '/partner/services'
    | '/staff/access'
    | '/staff/content'
    | '/staff/inquiries'
    | '/partner/'
    | '/staff/'
    | '/workspace/'
    | '/admin/review/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/directory'
    | '/early-stage-founders'
    | '/faq'
    | '/for-partners'
    | '/for-universities'
    | '/how-it-works'
    | '/immigrant-founders'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/join/$code'
    | '/nexus/help'
    | '/platform/ai'
    | '/platform/core'
    | '/platform/flow'
    | '/platform/grid'
    | '/platform/launch'
    | '/platform/nexus'
    | '/platform/os'
    | '/platform/studio'
    | '/platform/vault'
    | '/platform'
    | '/admin/applications'
    | '/admin/preview'
    | '/nexus/directory'
    | '/partner/apply'
    | '/partner/onboarding'
    | '/partner/profile'
    | '/partner/services'
    | '/staff/access'
    | '/staff/content'
    | '/staff/inquiries'
    | '/partner'
    | '/staff'
    | '/workspace'
    | '/admin/review/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/directory'
    | '/early-stage-founders'
    | '/faq'
    | '/for-partners'
    | '/for-universities'
    | '/how-it-works'
    | '/immigrant-founders'
    | '/platform'
    | '/privacy'
    | '/reset-password'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/join/$code'
    | '/nexus/help'
    | '/platform/ai'
    | '/platform/core'
    | '/platform/flow'
    | '/platform/grid'
    | '/platform/launch'
    | '/platform/nexus'
    | '/platform/os'
    | '/platform/studio'
    | '/platform/vault'
    | '/platform/'
    | '/_authenticated/admin/applications'
    | '/_authenticated/admin/preview'
    | '/_authenticated/nexus/directory'
    | '/_authenticated/partner/apply'
    | '/_authenticated/partner/onboarding'
    | '/_authenticated/partner/profile'
    | '/_authenticated/partner/services'
    | '/_authenticated/staff/access'
    | '/_authenticated/staff/content'
    | '/_authenticated/staff/inquiries'
    | '/_authenticated/partner/'
    | '/_authenticated/staff/'
    | '/_authenticated/workspace/'
    | '/_authenticated/admin/review/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DirectoryRoute: typeof DirectoryRoute
  EarlyStageFoundersRoute: typeof EarlyStageFoundersRoute
  FaqRoute: typeof FaqRoute
  ForPartnersRoute: typeof ForPartnersRoute
  ForUniversitiesRoute: typeof ForUniversitiesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ImmigrantFoundersRoute: typeof ImmigrantFoundersRoute
  PlatformRoute: typeof PlatformRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  JoinCodeRoute: typeof JoinCodeRoute
  NexusHelpRoute: typeof NexusHelpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/immigrant-founders': {
      id: '/immigrant-founders'
      path: '/immigrant-founders'
      fullPath: '/immigrant-founders'
      preLoaderRoute: typeof ImmigrantFoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-universities': {
      id: '/for-universities'
      path: '/for-universities'
      fullPath: '/for-universities'
      preLoaderRoute: typeof ForUniversitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-partners': {
      id: '/for-partners'
      path: '/for-partners'
      fullPath: '/for-partners'
      preLoaderRoute: typeof ForPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/early-stage-founders': {
      id: '/early-stage-founders'
      path: '/early-stage-founders'
      fullPath: '/early-stage-founders'
      preLoaderRoute: typeof EarlyStageFoundersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/': {
      id: '/platform/'
      path: '/'
      fullPath: '/platform/'
      preLoaderRoute: typeof PlatformIndexRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/vault': {
      id: '/platform/vault'
      path: '/vault'
      fullPath: '/platform/vault'
      preLoaderRoute: typeof PlatformVaultRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/studio': {
      id: '/platform/studio'
      path: '/studio'
      fullPath: '/platform/studio'
      preLoaderRoute: typeof PlatformStudioRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/os': {
      id: '/platform/os'
      path: '/os'
      fullPath: '/platform/os'
      preLoaderRoute: typeof PlatformOsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/nexus': {
      id: '/platform/nexus'
      path: '/nexus'
      fullPath: '/platform/nexus'
      preLoaderRoute: typeof PlatformNexusRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/launch': {
      id: '/platform/launch'
      path: '/launch'
      fullPath: '/platform/launch'
      preLoaderRoute: typeof PlatformLaunchRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/grid': {
      id: '/platform/grid'
      path: '/grid'
      fullPath: '/platform/grid'
      preLoaderRoute: typeof PlatformGridRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/flow': {
      id: '/platform/flow'
      path: '/flow'
      fullPath: '/platform/flow'
      preLoaderRoute: typeof PlatformFlowRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/core': {
      id: '/platform/core'
      path: '/core'
      fullPath: '/platform/core'
      preLoaderRoute: typeof PlatformCoreRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/ai': {
      id: '/platform/ai'
      path: '/ai'
      fullPath: '/platform/ai'
      preLoaderRoute: typeof PlatformAiRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/nexus/help': {
      id: '/nexus/help'
      path: '/nexus/help'
      fullPath: '/nexus/help'
      preLoaderRoute: typeof NexusHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/': {
      id: '/_authenticated/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthenticatedStaffIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/': {
      id: '/_authenticated/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof AuthenticatedPartnerIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/inquiries': {
      id: '/_authenticated/staff/inquiries'
      path: '/staff/inquiries'
      fullPath: '/staff/inquiries'
      preLoaderRoute: typeof AuthenticatedStaffInquiriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/content': {
      id: '/_authenticated/staff/content'
      path: '/staff/content'
      fullPath: '/staff/content'
      preLoaderRoute: typeof AuthenticatedStaffContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/staff/access': {
      id: '/_authenticated/staff/access'
      path: '/staff/access'
      fullPath: '/staff/access'
      preLoaderRoute: typeof AuthenticatedStaffAccessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/services': {
      id: '/_authenticated/partner/services'
      path: '/partner/services'
      fullPath: '/partner/services'
      preLoaderRoute: typeof AuthenticatedPartnerServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/profile': {
      id: '/_authenticated/partner/profile'
      path: '/partner/profile'
      fullPath: '/partner/profile'
      preLoaderRoute: typeof AuthenticatedPartnerProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/onboarding': {
      id: '/_authenticated/partner/onboarding'
      path: '/partner/onboarding'
      fullPath: '/partner/onboarding'
      preLoaderRoute: typeof AuthenticatedPartnerOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partner/apply': {
      id: '/_authenticated/partner/apply'
      path: '/partner/apply'
      fullPath: '/partner/apply'
      preLoaderRoute: typeof AuthenticatedPartnerApplyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nexus/directory': {
      id: '/_authenticated/nexus/directory'
      path: '/nexus/directory'
      fullPath: '/nexus/directory'
      preLoaderRoute: typeof AuthenticatedNexusDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/preview': {
      id: '/_authenticated/admin/preview'
      path: '/admin/preview'
      fullPath: '/admin/preview'
      preLoaderRoute: typeof AuthenticatedAdminPreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/applications': {
      id: '/_authenticated/admin/applications'
      path: '/admin/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/review/$id': {
      id: '/_authenticated/admin/review/$id'
      path: '/admin/review/$id'
      fullPath: '/admin/review/$id'
      preLoaderRoute: typeof AuthenticatedAdminReviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminApplicationsRoute: typeof AuthenticatedAdminApplicationsRoute
  AuthenticatedAdminPreviewRoute: typeof AuthenticatedAdminPreviewRoute
  AuthenticatedNexusDirectoryRoute: typeof AuthenticatedNexusDirectoryRoute
  AuthenticatedPartnerApplyRoute: typeof AuthenticatedPartnerApplyRoute
  AuthenticatedPartnerOnboardingRoute: typeof AuthenticatedPartnerOnboardingRoute
  AuthenticatedPartnerProfileRoute: typeof AuthenticatedPartnerProfileRoute
  AuthenticatedPartnerServicesRoute: typeof AuthenticatedPartnerServicesRoute
  AuthenticatedStaffAccessRoute: typeof AuthenticatedStaffAccessRoute
  AuthenticatedStaffContentRoute: typeof AuthenticatedStaffContentRoute
  AuthenticatedStaffInquiriesRoute: typeof AuthenticatedStaffInquiriesRoute
  AuthenticatedPartnerIndexRoute: typeof AuthenticatedPartnerIndexRoute
  AuthenticatedStaffIndexRoute: typeof AuthenticatedStaffIndexRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
  AuthenticatedAdminReviewIdRoute: typeof AuthenticatedAdminReviewIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminApplicationsRoute: AuthenticatedAdminApplicationsRoute,
  AuthenticatedAdminPreviewRoute: AuthenticatedAdminPreviewRoute,
  AuthenticatedNexusDirectoryRoute: AuthenticatedNexusDirectoryRoute,
  AuthenticatedPartnerApplyRoute: AuthenticatedPartnerApplyRoute,
  AuthenticatedPartnerOnboardingRoute: AuthenticatedPartnerOnboardingRoute,
  AuthenticatedPartnerProfileRoute: AuthenticatedPartnerProfileRoute,
  AuthenticatedPartnerServicesRoute: AuthenticatedPartnerServicesRoute,
  AuthenticatedStaffAccessRoute: AuthenticatedStaffAccessRoute,
  AuthenticatedStaffContentRoute: AuthenticatedStaffContentRoute,
  AuthenticatedStaffInquiriesRoute: AuthenticatedStaffInquiriesRoute,
  AuthenticatedPartnerIndexRoute: AuthenticatedPartnerIndexRoute,
  AuthenticatedStaffIndexRoute: AuthenticatedStaffIndexRoute,
  AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  AuthenticatedAdminReviewIdRoute: AuthenticatedAdminReviewIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PlatformRouteChildren {
  PlatformAiRoute: typeof PlatformAiRoute
  PlatformCoreRoute: typeof PlatformCoreRoute
  PlatformFlowRoute: typeof PlatformFlowRoute
  PlatformGridRoute: typeof PlatformGridRoute
  PlatformLaunchRoute: typeof PlatformLaunchRoute
  PlatformNexusRoute: typeof PlatformNexusRoute
  PlatformOsRoute: typeof PlatformOsRoute
  PlatformStudioRoute: typeof PlatformStudioRoute
  PlatformVaultRoute: typeof PlatformVaultRoute
  PlatformIndexRoute: typeof PlatformIndexRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformAiRoute: PlatformAiRoute,
  PlatformCoreRoute: PlatformCoreRoute,
  PlatformFlowRoute: PlatformFlowRoute,
  PlatformGridRoute: PlatformGridRoute,
  PlatformLaunchRoute: PlatformLaunchRoute,
  PlatformNexusRoute: PlatformNexusRoute,
  PlatformOsRoute: PlatformOsRoute,
  PlatformStudioRoute: PlatformStudioRoute,
  PlatformVaultRoute: PlatformVaultRoute,
  PlatformIndexRoute: PlatformIndexRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DirectoryRoute: DirectoryRoute,
  EarlyStageFoundersRoute: EarlyStageFoundersRoute,
  FaqRoute: FaqRoute,
  ForPartnersRoute: ForPartnersRoute,
  ForUniversitiesRoute: ForUniversitiesRoute,
  HowItWorksRoute: HowItWorksRoute,
  ImmigrantFoundersRoute: ImmigrantFoundersRoute,
  PlatformRoute: PlatformRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  JoinCodeRoute: JoinCodeRoute,
  NexusHelpRoute: NexusHelpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
